#!/bin/bash
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YPL037C_YDR252W/Run_Rooted_Codon_Free_Tau_YPL037C_YDR252W_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YPL037C_YDR252W/Run_Rooted_Codon_Force_Tau_YPL037C_YDR252W_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YPL037C_YDR252W/Run_UnRooted_Codon_Free_Tau_YPL037C_YDR252W_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YPL037C_YDR252W/Run_UnRooted_Codon_Force_Tau_YPL037C_YDR252W_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YMR143W_YDL083C/Run_Rooted_Codon_Free_Tau_YMR143W_YDL083C_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YMR143W_YDL083C/Run_Rooted_Codon_Force_Tau_YMR143W_YDL083C_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YMR143W_YDL083C/Run_UnRooted_Codon_Free_Tau_YMR143W_YDL083C_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YMR143W_YDL083C/Run_UnRooted_Codon_Force_Tau_YMR143W_YDL083C_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YPR159W_YGR143W/Run_Rooted_Codon_Free_Tau_YPR159W_YGR143W_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YPR159W_YGR143W/Run_Rooted_Codon_Force_Tau_YPR159W_YGR143W_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YPR159W_YGR143W/Run_UnRooted_Codon_Free_Tau_YPR159W_YGR143W_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YPR159W_YGR143W/Run_UnRooted_Codon_Force_Tau_YPR159W_YGR143W_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YJL177W_YKL180W/Run_Rooted_Codon_Free_Tau_YJL177W_YKL180W_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YJL177W_YKL180W/Run_Rooted_Codon_Force_Tau_YJL177W_YKL180W_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YJL177W_YKL180W/Run_UnRooted_Codon_Free_Tau_YJL177W_YKL180W_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YJL177W_YKL180W/Run_UnRooted_Codon_Force_Tau_YJL177W_YKL180W_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YGL133W_YPL216W/Run_Rooted_Codon_Free_Tau_YGL133W_YPL216W_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YGL133W_YPL216W/Run_Rooted_Codon_Force_Tau_YGL133W_YPL216W_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YGL133W_YPL216W/Run_UnRooted_Codon_Free_Tau_YGL133W_YPL216W_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YGL133W_YPL216W/Run_UnRooted_Codon_Force_Tau_YGL133W_YPL216W_script.sh
