#!/bin/bash
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YJR048W_YEL039C/Run_Rooted_Codon_Free_Tau_YJR048W_YEL039C_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YJR048W_YEL039C/Run_Rooted_Codon_Force_Tau_YJR048W_YEL039C_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YJR048W_YEL039C/Run_UnRooted_Codon_Free_Tau_YJR048W_YEL039C_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YJR048W_YEL039C/Run_UnRooted_Codon_Force_Tau_YJR048W_YEL039C_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YBR191W_YPL079W/Run_Rooted_Codon_Free_Tau_YBR191W_YPL079W_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YBR191W_YPL079W/Run_Rooted_Codon_Force_Tau_YBR191W_YPL079W_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YBR191W_YPL079W/Run_UnRooted_Codon_Free_Tau_YBR191W_YPL079W_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YBR191W_YPL079W/Run_UnRooted_Codon_Force_Tau_YBR191W_YPL079W_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YER074W_YIL069C/Run_Rooted_Codon_Free_Tau_YER074W_YIL069C_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YER074W_YIL069C/Run_Rooted_Codon_Force_Tau_YER074W_YIL069C_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YER074W_YIL069C/Run_UnRooted_Codon_Free_Tau_YER074W_YIL069C_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YER074W_YIL069C/Run_UnRooted_Codon_Force_Tau_YER074W_YIL069C_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YDR418W_YEL054C/Run_Rooted_Codon_Free_Tau_YDR418W_YEL054C_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YDR418W_YEL054C/Run_Rooted_Codon_Force_Tau_YDR418W_YEL054C_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YDR418W_YEL054C/Run_UnRooted_Codon_Free_Tau_YDR418W_YEL054C_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YDR418W_YEL054C/Run_UnRooted_Codon_Force_Tau_YDR418W_YEL054C_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YNL049C_YIL109C/Run_Rooted_Codon_Free_Tau_YNL049C_YIL109C_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YNL049C_YIL109C/Run_Rooted_Codon_Force_Tau_YNL049C_YIL109C_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YNL049C_YIL109C/Run_UnRooted_Codon_Free_Tau_YNL049C_YIL109C_script.sh
sbatch -o CodonGeneconv-%j.out -p bigmem -w node92 --mail-type=FAIL --mail-user=xji3@ncsu.edu ./YNL049C_YIL109C/Run_UnRooted_Codon_Force_Tau_YNL049C_YIL109C_script.sh
