#!/bin/bash
python get_site_posterior.py --paralog1 YDR518W --paralog2 YCL043C --model HKY --clock --force --no-dir --no-gBGC
python get_site_posterior.py --paralog1 YDR518W --paralog2 YCL043C --model HKY --clock --no-force --no-dir --no-gBGC
python get_site_posterior.py --paralog1 YDR518W --paralog2 YCL043C --model HKY --clock --no-force --no-dir --gBGC
python get_site_posterior.py --paralog1 YDR518W --paralog2 YCL043C --model HKY --clock --no-force --dir --no-gBGC
python get_site_posterior.py --paralog1 YDR518W --paralog2 YCL043C --model HKY --clock --no-force --dir --gBGC
python get_site_posterior.py --paralog1 YDR518W --paralog2 YCL043C --model HKY --no-clock --force --no-dir --no-gBGC
python get_site_posterior.py --paralog1 YDR518W --paralog2 YCL043C --model HKY --no-clock --no-force --no-dir --no-gBGC
python get_site_posterior.py --paralog1 YDR518W --paralog2 YCL043C --model HKY --no-clock --no-force --no-dir --gBGC
python get_site_posterior.py --paralog1 YDR518W --paralog2 YCL043C --model HKY --no-clock --no-force --dir --no-gBGC
python get_site_posterior.py --paralog1 YDR518W --paralog2 YCL043C --model HKY --no-clock --no-force --dir --gBGC
python get_site_posterior.py --paralog1 YDR518W --paralog2 YCL043C --model MG94 --clock --force --no-dir --no-gBGC
python get_site_posterior.py --paralog1 YDR518W --paralog2 YCL043C --model MG94 --clock --no-force --no-dir --no-gBGC
python get_site_posterior.py --paralog1 YDR518W --paralog2 YCL043C --model MG94 --clock --no-force --no-dir --gBGC
python get_site_posterior.py --paralog1 YDR518W --paralog2 YCL043C --model MG94 --clock --no-force --dir --no-gBGC
python get_site_posterior.py --paralog1 YDR518W --paralog2 YCL043C --model MG94 --clock --no-force --dir --gBGC
python get_site_posterior.py --paralog1 YDR518W --paralog2 YCL043C --model MG94 --no-clock --force --no-dir --no-gBGC
python get_site_posterior.py --paralog1 YDR518W --paralog2 YCL043C --model MG94 --no-clock --no-force --no-dir --no-gBGC
python get_site_posterior.py --paralog1 YDR518W --paralog2 YCL043C --model MG94 --no-clock --no-force --no-dir --gBGC
python get_site_posterior.py --paralog1 YDR518W --paralog2 YCL043C --model MG94 --no-clock --no-force --dir --no-gBGC
python get_site_posterior.py --paralog1 YDR518W --paralog2 YCL043C --model MG94 --no-clock --no-force --dir --gBGC
