---
title: "Check_MLE"
author: "Xiang Ji"
date: "March 20, 2015"
output: html_document
---

This R script is used for checking MLE of the Geneconv project

1, Read in tables
```{r}
rm(list=ls())  # clean up workspace
setwd("/Users/xji3/Genconv/NewClusterPackRun")
path.HKY <- "/Users/xji3/FromCluster03232015_4/NewPackageNewRun/"
path.MG94 <- "/Users/xji3/FromCluster03212015/NewPackageNewRun/"
#path.HKY <- path.MG94
#path.MG94 = path.HKY
#path <- "G:/Geneconv/NewClusterPackRun/NewPackageNewRun/"
#HKY_clock_summary <- "HKY_clock_summary"
summary.list.MG94 <- c( 
                  "MG94_clock_summary",
                  "MG94_nonclock_summary", 
                  "Force_MG94_clock_summary", 
                  "Force_MG94_nonclock_summary"
                  )
summary.list.HKY <- c( "HKY_nonclock_summary",
                  "HKY_clock_summary",
                  "Force_HKY_clock_summary", 
                 "Force_HKY_nonclock_summary"
                  )
#summary.list <- c("Force_MG94_clock_summary")
for (target.summary in summary.list.MG94){
  summary_file <- paste(path.MG94, target.summary, '.txt', sep = '')
  all <- readLines(summary_file, n = -1)
  col.names <- strsplit(all[1], ' ')[[1]][-1]
  row.names <- strsplit(all[length(all)], ' ')[[1]][-1]
  summary_mat <- as.matrix(read.table(summary_file, 
                                        row.names = row.names, 
                                        col.names = col.names))
  assign(target.summary, summary_mat)
}

for (target.summary in summary.list.HKY){
  summary_file <- paste(path.HKY, target.summary, '.txt', sep = '')
  all <- readLines(summary_file, n = -1)
  col.names <- strsplit(all[1], ' ')[[1]][-1]
  row.names <- strsplit(all[length(all)], ' ')[[1]][-1]
  summary_mat <- as.matrix(read.table(summary_file, 
                                        row.names = row.names, 
                                        col.names = col.names))
  assign(target.summary, summary_mat)
}

# read in directional model summary
summary.list.Dir <- c( 
                  "MG94_clock_summary",
                  "MG94_nonclock_summary"
                  )
for (target.summary in summary.list.Dir){
  summary_file <- paste(path.MG94, "Dir_" , target.summary, '.txt', sep = '')
  all <- readLines(summary_file, n = -1)
  col.names <- strsplit(all[1], ' ')[[1]][-1]
  row.names <- strsplit(all[length(all)], ' ')[[1]][-1]
  summary_mat <- as.matrix(read.table(summary_file, 
                                        row.names = row.names, 
                                        col.names = col.names))
  assign(paste("Dir_", target.summary, sep = ''), summary_mat)
  write.table(gsub("_", ".", paste("Dir_", target.summary, sep = '')), 
              paste(path.MG94, "Dir_", target.summary, sep = ''))
}

# read in directional model summary
summary.list.Dir <- c( 
                  "HKY_nonclock_summary",
                  "HKY_clock_summary"
                  )
for (target.summary in summary.list.Dir){
  summary_file <- paste(path.HKY, "Dir_" , target.summary, '.txt', sep = '')
  all <- readLines(summary_file, n = -1)
  col.names <- strsplit(all[1], ' ')[[1]][-1]
  row.names <- strsplit(all[length(all)], ' ')[[1]][-1]
  summary_mat <- as.matrix(read.table(summary_file, 
                                        row.names = row.names, 
                                        col.names = col.names))
  assign(paste("Dir_", target.summary, sep = ''), summary_mat)
  write.table(gsub("_", ".", paste("Dir_", target.summary, sep = '')), 
              paste(path.HKY, "Dir_", target.summary, sep = ''))
}



# read in gBGC model summary
summary.list.gBGC <- c( 
                  "MG94_clock_summary",
                  "MG94_nonclock_summary"
                  )
for (target.summary in summary.list.gBGC){
  summary_file <- paste(path.MG94, "gBGC_" , target.summary, '.txt', sep = '')
  all <- readLines(summary_file, n = -1)
  col.names <- strsplit(all[1], ' ')[[1]][-1]
  row.names <- strsplit(all[length(all)], ' ')[[1]][-1]
  summary_mat <- as.matrix(read.table(summary_file, 
                                        row.names = row.names, 
                                        col.names = col.names))
  assign(paste("gBGC_", target.summary, sep = ''), summary_mat)
  write.table(gsub("_", ".", paste("gBGC_", target.summary, sep = '')), 
              paste(path.MG94, "gBGC_", target.summary, sep = ''))
}

# read in Dir gBGC model summary
summary.list.gBGC <- c( 
                  "MG94_clock_summary",
                  "MG94_nonclock_summary"
                  )
for (target.summary in summary.list.gBGC){
  summary_file <- paste(path.MG94, "Dir_gBGC_" , target.summary, '.txt', sep = '')
  all <- readLines(summary_file, n = -1)
  col.names <- strsplit(all[1], ' ')[[1]][-1]
  row.names <- strsplit(all[length(all)], ' ')[[1]][-1]
  summary_mat <- as.matrix(read.table(summary_file, 
                                        row.names = row.names, 
                                        col.names = col.names))
  assign(paste("Dir_gBGC_", target.summary, sep = ''), summary_mat)
  write.table(gsub("_", ".", paste("Dir_gBGC_", target.summary, sep = '')), 
              paste(path.MG94, "Dir_gBGC_", target.summary, sep = ''))
}

# read in gBGC model summary
summary.list.gBGC <- c( 
                  "HKY_nonclock_summary",
                  "HKY_clock_summary"
                  )
for (target.summary in summary.list.gBGC){
  summary_file <- paste(path.HKY, "gBGC_" , target.summary, '.txt', sep = '')
  all <- readLines(summary_file, n = -1)
  col.names <- strsplit(all[1], ' ')[[1]][-1]
  row.names <- strsplit(all[length(all)], ' ')[[1]][-1]
  summary_mat <- as.matrix(read.table(summary_file, 
                                        row.names = row.names, 
                                        col.names = col.names))
  assign(paste("gBGC_", target.summary, sep = ''), summary_mat)
  write.table(gsub("_", ".", paste("gBGC_", target.summary, sep = '')), 
              paste(path.HKY, "gBGC_", target.summary, sep = ''))
}

# read in Dir gBGC model summary
summary.list.gBGC <- c( 
                  "HKY_nonclock_summary",
                  "HKY_clock_summary"
                  )
for (target.summary in summary.list.gBGC){
  summary_file <- paste(path.HKY, "Dir_gBGC_" , target.summary, '.txt', sep = '')
  all <- readLines(summary_file, n = -1)
  col.names <- strsplit(all[1], ' ')[[1]][-1]
  row.names <- strsplit(all[length(all)], ' ')[[1]][-1]
  summary_mat <- as.matrix(read.table(summary_file, 
                                        row.names = row.names, 
                                        col.names = col.names))
  assign(paste("Dir_gBGC_", target.summary, sep = ''), summary_mat)
  write.table(gsub("_", ".", paste("Dir_gBGC_", target.summary, sep = '')), 
              paste(path.HKY, "Dir_gBGC_", target.summary, sep = ''))
}

```


```{r}
check.suspicious <- function(sh.file, summary, model, clock, gBGC, dir, force, threshold = 1e-4){
  rerun <- file(sh.file, "a")
  sh.prefix <- "sbatch -o suspicious-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu"
  sh.suffix <- "_"
  if (dir) {
    dir.cmd <- "--dir"
    sh.suffix <- paste(sh.suffix, "dir_", sep = "")
    } else {dir.cmd <- "--no-dir"}
  if (gBGC) {
    gBGC.cmd <- "--gBGC"
    sh.suffix <- paste(sh.suffix, "gBGC_", sep = "")
    } else gBGC.cmd <- "--no-gBGC"
  sh.suffix <- paste(sh.suffix, model, "_", sep = "")
  if (clock)  {  
    clock.cmd <- "--clock"
    sh.suffix <- paste(sh.suffix, "clock_", sep = "")
    }  else {
      clock.cmd <- "--no-clock"
      sh.suffix <- paste(sh.suffix, "nonclock_", sep = "")
      }
  if (force) { 
    force.cmd <- "--force"
    sh.suffix <- paste(sh.suffix, "force_", sep = "")
    }  else force.cmd <- "--no-force"
  
  idx <- which(rownames(summary) %in% "(N0,kluyveri)")
  print(colnames(summary)[(summary[idx, ] < threshold)])
  for( pair in colnames(summary)[(summary[idx, ] < threshold)]){
    paralog <- strsplit(pair, split = "_")[[1]]
    pair.sh.name <- paste("./NewRun/", pair, sh.suffix, "suspicious.sh", sep = "")
    pair.sh <- file(pair.sh.name, "w+")
    txt.suffix <- paste(pair, sh.suffix, "suspicious_PrintScreen.txt", sep = "")
    sh.txt <- paste("python", "Run_unfinished.py", 
    #sh.txt <- paste("/Library/Frameworks/Python.framework/Versions/7.3/bin/python", "Run_unfinished.py", 
                    "--paralog1", paralog[1], "--paralog2", paralog[2], 
                    force.cmd, gBGC.cmd, dir.cmd, clock.cmd, "--model", model, 
                    ">", txt.suffix, sep = " ")
    writeLines(c("#!/bin/bash", sh.txt), pair.sh)
    close(pair.sh)
    writeLines(paste(sh.prefix, pair.sh.name, sep = " "), rerun.sh)
    #writeLines(cbind(paste("chmod +x", pair.sh.name, sep = " "), pair.sh.name), rerun.sh)
    }
  close(rerun.sh)
}
```

Now generate .sh files to re-run the suspicious pairs.

```{r}
sh.file <- "./Rerun_Suspicious.sh"
rerun.sh <- file(sh.file, "w+")
writeLines("#!/bin/bash", rerun.sh)
close(rerun.sh)
threshold <- 1e-3
# MG94 Models
# Dir gBGC MG94 Clock
check.suspicious(sh.file, summary = Dir_gBGC_MG94_clock_summary, model = "MG94",clock = TRUE, gBGC = TRUE,
                 dir = TRUE, force = FALSE, threshold = threshold)
# Dir gBGC MG94 nonClock
check.suspicious(sh.file, summary = Dir_gBGC_MG94_nonclock_summary, model = "MG94",clock = FALSE, gBGC = TRUE,
                 dir = TRUE, force = FALSE, threshold = threshold)

# gBGC MG94 Clock
check.suspicious(sh.file, summary = gBGC_MG94_clock_summary, model = "MG94",clock = TRUE, gBGC = TRUE,
                 dir = FALSE, force = FALSE, threshold = threshold)
# gBGC MG94 nonClock
check.suspicious(sh.file, summary = gBGC_MG94_nonclock_summary, model = "MG94",clock = FALSE, gBGC = TRUE,
                 dir = FALSE, force = FALSE, threshold = threshold)

# Dir MG94 Clock
check.suspicious(sh.file, summary = Dir_MG94_clock_summary, model = "MG94",clock = TRUE, gBGC = FALSE,
                 dir = TRUE, force = FALSE, threshold = threshold)
# Dir MG94 nonClock
check.suspicious(sh.file, summary = Dir_MG94_nonclock_summary, model = "MG94",clock = FALSE, gBGC = FALSE,
                 dir = TRUE, force = FALSE, threshold = threshold)

# MG94 Clock
check.suspicious(sh.file, summary = MG94_clock_summary, model = "MG94",clock = TRUE, gBGC = FALSE,
                 dir = FALSE, force = FALSE, threshold = threshold)
# MG94 nonClock
check.suspicious(sh.file, summary = MG94_nonclock_summary, model = "MG94",clock = FALSE, gBGC = FALSE,
                 dir = FALSE, force = FALSE, threshold = threshold)

# MG94 Force Clock
check.suspicious(sh.file, summary = Force_MG94_clock_summary, model = "MG94",clock = TRUE, gBGC = FALSE,
                 dir = FALSE, force = TRUE, threshold = threshold)
# MG94 Force nonClock
check.suspicious(sh.file, summary = Force_MG94_nonclock_summary, model = "MG94",clock = FALSE, gBGC = FALSE,
                 dir = FALSE, force = TRUE, threshold = threshold)

# HKY Models 
# Dir gBGC HKY Clock
check.suspicious(sh.file, summary = Dir_gBGC_HKY_clock_summary, model = "HKY",clock = TRUE, gBGC = TRUE,
                 dir = TRUE, force = FALSE, threshold = threshold)
# Dir gBGC HKY nonClock
check.suspicious(sh.file, summary = Dir_gBGC_HKY_nonclock_summary, model = "HKY",clock = FALSE, gBGC = TRUE,
                 dir = TRUE, force = FALSE, threshold = threshold)

# gBGC HKY Clock
check.suspicious(sh.file, summary = gBGC_HKY_clock_summary, model = "HKY",clock = TRUE, gBGC = TRUE,
                 dir = FALSE, force = FALSE, threshold = threshold)
# gBGC HKY nonClock
check.suspicious(sh.file, summary = gBGC_HKY_nonclock_summary, model = "HKY",clock = FALSE, gBGC = TRUE,
                 dir = FALSE, force = FALSE, threshold = threshold)

# Dir HKY Clock
check.suspicious(sh.file, summary = Dir_HKY_clock_summary, model = "HKY",clock = TRUE, gBGC = FALSE,
                 dir = TRUE, force = FALSE, threshold = threshold)
# Dir HKY nonClock
check.suspicious(sh.file, summary = Dir_HKY_nonclock_summary, model = "HKY",clock = FALSE, gBGC = FALSE,
                 dir = TRUE, force = FALSE, threshold = threshold)

# HKY Clock
check.suspicious(sh.file, summary = HKY_clock_summary, model = "HKY",clock = TRUE, gBGC = FALSE,
                 dir = FALSE, force = FALSE, threshold = threshold)
# HKY nonClock
check.suspicious(sh.file, summary = HKY_nonclock_summary, model = "HKY",clock = FALSE, gBGC = FALSE,
                 dir = FALSE, force = FALSE, threshold = threshold)

# HKY Force Clock
check.suspicious(sh.file, summary = Force_HKY_clock_summary, model = "HKY",clock = TRUE, gBGC = FALSE,
                 dir = FALSE, force = TRUE, threshold = threshold)
# HKY Force nonClock
check.suspicious(sh.file, summary = Force_HKY_nonclock_summary, model = "HKY",clock = FALSE, gBGC = FALSE,
                 dir = FALSE, force = TRUE, threshold = threshold)
  
```

Now check lnL improvements

```{r}
# nonclock models
# HKY
HKY_nonclock_summary[2, ] - Force_HKY_nonclock_summary[2, ]
Dir_HKY_nonclock_summary[2, ] - HKY_nonclock_summary[2, ]
gBGC_HKY_nonclock_summary[2, ] - HKY_nonclock_summary[2, ]
Dir_gBGC_HKY_nonclock_summary[2, ] - Dir_HKY_nonclock_summary[2, ]
Dir_gBGC_HKY_nonclock_summary[2, ] - gBGC_HKY_nonclock_summary[2, ]
# MG94
MG94_nonclock_summary[2, ] - Force_MG94_nonclock_summary[2, ]
Dir_MG94_nonclock_summary[2, ] - MG94_nonclock_summary[2, ]
gBGC_MG94_nonclock_summary[2, ] - MG94_nonclock_summary[2, ]
Dir_gBGC_MG94_nonclock_summary[2, ] - Dir_MG94_nonclock_summary[2, ]
Dir_gBGC_MG94_nonclock_summary[2, ] - gBGC_MG94_nonclock_summary[2, ]
```

```{r}
# clock models
# HKY
HKY_clock_summary[2, ] - Force_HKY_clock_summary[2, ]
Dir_HKY_clock_summary[2, ] - HKY_clock_summary[2, ]
gBGC_HKY_clock_summary[2, ] - HKY_clock_summary[2, ]
Dir_gBGC_HKY_clock_summary[2, ] - Dir_HKY_clock_summary[2, ]
Dir_gBGC_HKY_clock_summary[2, ] - gBGC_HKY_clock_summary[2, ]
# MG94
MG94_clock_summary[2, ] - Force_MG94_clock_summary[2, ]
Dir_MG94_clock_summary[2, ] - MG94_clock_summary[2, ]
#gBGC_MG94_clock_summary[2, ] - MG94_clock_summary[2, ]
Dir_gBGC_MG94_clock_summary[2, ] - Dir_MG94_clock_summary[2, ]
#Dir_gBGC_MG94_clock_summary[2, ] - gBGC_MG94_clock_summary[2, ]
```
