#!/bin/bash
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YLR406C_YDL075Wdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YER131W_YGL189Cdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YDR502C_YLR180Wdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YML026C_YDR450Wdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YNL301C_YOL120Cdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YHR106W_YDR353Wdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YIL057C_YER067Wdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YPL087W_YBR183Wdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YNL069C_YIL133Cdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YDR518W_YCL043Cdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YGR043C_YLR354Cdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YPR157W_YGR141Wdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YDR099W_YER177Wdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YBR024W_YBR037Cdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YPL037C_YDR252Wdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YMR143W_YDL083Cdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YPR159W_YGR143Wdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YJL177W_YKL180Wdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YGL133W_YPL216Wdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YJR048W_YEL039Cdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YBR191W_YPL079Wdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YER074W_YIL069Cdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YDR418W_YEL054Cdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YNL049C_YIL109Cdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YBR117C_YPR074Cdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YPL232W_YMR183Cdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YLR284C_YOR180Cdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YBL087C_YER117Wdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YGL062W_YBR218Cdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YIR033W_YKL020Cdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YMR243C_YOR316Cdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YLR333C_YGR027Cdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YMR142C_YDL082Wdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YER102W_YBL072Cdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YAL056W_YOR371Cdir_ForceTau.sh
sbatch -o cd-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YDR438W_YML018Cdir_ForceTau.sh
