---
title: "Fish_Report"
author: "Xiang Ji"
date: "June 8, 2015"
output: html_document
---

Fish Paralog: TLR5a_TLR5b (using only TIR domain)
Fish Tree: ((Zebrafish, Carp), Gar)

```{r}
rm(list=ls())  # clean up workspace
path.Fish <- "/Users/xji3/FromCluster06082015/ZebraFish/"
summary.list <- c( "HKY_",
                   "Force_HKY_",
                   "Dir_HKY_", 
                   "gBGC_HKY_",
                   "gBGC_Dir_HKY_",
                   "MG94_",
                   "Force_MG94_",
                   "Dir_MG94_", 
                   "gBGC_MG94_",
                   "gBGC_Dir_MG94_",
                   "switched_HKY_",
                   "switched_Force_HKY_",
                   "switched_Dir_HKY_", 
                   "switched_gBGC_HKY_",
                   "switched_gBGC_Dir_HKY_",
                   "switched_MG94_",
                   "switched_Force_MG94_",
                   "switched_Dir_MG94_", 
                   "switched_gBGC_MG94_",
                   "switched_gBGC_Dir_MG94_"
                   )
pair <- "TLR5a_TLR5b"
suffix.list <- c("_clock_summary.txt")
for (summary in summary.list){
  summary_file <- paste(path.Fish, summary, pair, suffix.list[1], sep = '')
  all <- readLines(summary_file, n = -1)
  #col.names <- strsplit(all[1], ' ')[[1]][-1]
  row.names <- strsplit(all[length(all)], ' ')[[1]][-1]
  summary_mat <- as.matrix(read.table(summary_file, 
                                      row.names = row.names, 
                                      col.names = paste(summary, pair, sep = "")
                                      ))
  assign(paste(summary, pair, sep = ""), summary_mat)
}

```

####Now compare clock model results

#####lnL increase

```{r}
#HKY model
HKY_TLR5a_TLR5b[2] - Force_HKY_TLR5a_TLR5b[2]
Dir_HKY_TLR5a_TLR5b[2] - HKY_TLR5a_TLR5b[2]
gBGC_HKY_TLR5a_TLR5b[2] - HKY_TLR5a_TLR5b[2]
gBGC_Dir_HKY_TLR5a_TLR5b[2] - Dir_HKY_TLR5a_TLR5b[2]
gBGC_Dir_HKY_TLR5a_TLR5b[2] - gBGC_HKY_TLR5a_TLR5b[2]

#MG94 model
MG94_TLR5a_TLR5b[2] - Force_MG94_TLR5a_TLR5b[2]
Dir_MG94_TLR5a_TLR5b[2] - MG94_TLR5a_TLR5b[2]
gBGC_MG94_TLR5a_TLR5b[2] - MG94_TLR5a_TLR5b[2]
gBGC_Dir_MG94_TLR5a_TLR5b[2] - Dir_MG94_TLR5a_TLR5b[2]
gBGC_Dir_MG94_TLR5a_TLR5b[2] - gBGC_MG94_TLR5a_TLR5b[2]

```

#####lnL difference between real and control (switched paralog sequence)
```{r}
#HKY model
Force_HKY_TLR5a_TLR5b[2] - switched_Force_HKY_TLR5a_TLR5b[2]  # This should be zero
HKY_TLR5a_TLR5b[2] - switched_HKY_TLR5a_TLR5b[2]
Dir_HKY_TLR5a_TLR5b[2] - switched_Dir_HKY_TLR5a_TLR5b[2]
gBGC_HKY_TLR5a_TLR5b[2] - switched_gBGC_HKY_TLR5a_TLR5b[2]
gBGC_Dir_HKY_TLR5a_TLR5b[2] - switched_gBGC_Dir_HKY_TLR5a_TLR5b[2]

#MG94 model
Force_MG94_TLR5a_TLR5b[2] - switched_Force_MG94_TLR5a_TLR5b[2]  # This should be zero
MG94_TLR5a_TLR5b[2] - switched_MG94_TLR5a_TLR5b[2]
Dir_MG94_TLR5a_TLR5b[2] - switched_Dir_MG94_TLR5a_TLR5b[2]
gBGC_MG94_TLR5a_TLR5b[2] - switched_gBGC_MG94_TLR5a_TLR5b[2]
gBGC_Dir_MG94_TLR5a_TLR5b[2] - switched_gBGC_Dir_MG94_TLR5a_TLR5b[2]
```

#####Tau estimate difference between real and control (switched paralog sequence)
display the estimate of both cases followed by their difference
```{r}
#HKY model
print(paste(HKY_TLR5a_TLR5b["tau", 1], switched_HKY_TLR5a_TLR5b["tau", 1], HKY_TLR5a_TLR5b["tau", 1] - switched_HKY_TLR5a_TLR5b["tau", 1]))
print(paste(Dir_HKY_TLR5a_TLR5b["tau12", 1], switched_Dir_HKY_TLR5a_TLR5b["tau12", 1], Dir_HKY_TLR5a_TLR5b["tau12", 1] - switched_Dir_HKY_TLR5a_TLR5b["tau12", 1]))
print(paste(Dir_HKY_TLR5a_TLR5b["tau21", 1], switched_Dir_HKY_TLR5a_TLR5b["tau21", 1], Dir_HKY_TLR5a_TLR5b["tau21", 1] - switched_Dir_HKY_TLR5a_TLR5b["tau21", 1]))
print(paste(gBGC_HKY_TLR5a_TLR5b["tau", 1], switched_gBGC_HKY_TLR5a_TLR5b["tau", 1], gBGC_HKY_TLR5a_TLR5b["tau", 1] - switched_gBGC_HKY_TLR5a_TLR5b["tau", 1]))
print(paste(gBGC_Dir_HKY_TLR5a_TLR5b["tau12", 1], switched_gBGC_Dir_HKY_TLR5a_TLR5b["tau12", 1], gBGC_Dir_HKY_TLR5a_TLR5b["tau12", 1] - switched_gBGC_Dir_HKY_TLR5a_TLR5b["tau12", 1]))
print(paste(gBGC_Dir_HKY_TLR5a_TLR5b["tau21", 1], switched_gBGC_Dir_HKY_TLR5a_TLR5b["tau21", 1], gBGC_Dir_HKY_TLR5a_TLR5b["tau21", 1] - switched_gBGC_Dir_HKY_TLR5a_TLR5b["tau21", 1]))

#MG94 model
print(paste(MG94_TLR5a_TLR5b["tau", 1], switched_MG94_TLR5a_TLR5b["tau", 1], MG94_TLR5a_TLR5b["tau", 1] - switched_MG94_TLR5a_TLR5b["tau", 1]))
print(paste(Dir_MG94_TLR5a_TLR5b["tau12", 1], switched_Dir_MG94_TLR5a_TLR5b["tau12", 1], Dir_MG94_TLR5a_TLR5b["tau12", 1] - switched_Dir_MG94_TLR5a_TLR5b["tau12", 1]))
print(paste(Dir_MG94_TLR5a_TLR5b["tau21", 1], switched_Dir_MG94_TLR5a_TLR5b["tau21", 1], Dir_MG94_TLR5a_TLR5b["tau21", 1] - switched_Dir_MG94_TLR5a_TLR5b["tau21", 1]))
print(paste(gBGC_MG94_TLR5a_TLR5b["tau", 1], switched_gBGC_MG94_TLR5a_TLR5b["tau", 1], gBGC_MG94_TLR5a_TLR5b["tau", 1] - switched_gBGC_MG94_TLR5a_TLR5b["tau", 1]))
print(paste(gBGC_Dir_MG94_TLR5a_TLR5b["tau12", 1], switched_gBGC_Dir_MG94_TLR5a_TLR5b["tau12", 1], gBGC_Dir_MG94_TLR5a_TLR5b["tau12", 1] - switched_gBGC_Dir_MG94_TLR5a_TLR5b["tau12", 1]))
print(paste(gBGC_Dir_MG94_TLR5a_TLR5b["tau21", 1], switched_gBGC_Dir_MG94_TLR5a_TLR5b["tau21", 1], gBGC_Dir_MG94_TLR5a_TLR5b["tau21", 1] - switched_gBGC_Dir_MG94_TLR5a_TLR5b["tau21", 1]))
```