#!/bin/bash
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YLR406C_YDL075W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YER131W_YGL189C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YDR502C_YLR180W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YGL062W_YBR218C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YML026C_YDR450W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YNL301C_YOL120C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YHR106W_YDR353W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YIL057C_YER067W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YPL087W_YBR183W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YGR092W_YPR111W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YGR056W_YLR357W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YPL057C_YBR161W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YNL069C_YIL133C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YDR518W_YCL043C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YBL067C_YER098W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YPR157W_YGR141W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YMR053C_YKL072W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YDR099W_YER177W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YKR052C_YJL133W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YBR024W_YBR037C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YPL037C_YDR252W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YMR143W_YDL083C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YPR159W_YGR143W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YJL177W_YKL180W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YJR066W_YKL203C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YGL133W_YPL216W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YJR048W_YEL039C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YLR258W_YFR015C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YOR204W_YPL119C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YER074W_YIL069C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YBL056W_YER089C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YDR418W_YEL054C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YNL049C_YIL109C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YBR117C_YPR074C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YPL232W_YMR183C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YOR293W_YMR230W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YIR033W_YKL020C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YDR125C_YLR099C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YLR048W_YGR214W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YGR043C_YLR354C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YBL087C_YER117W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YGL101W_YBR242W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YDL061C_YLR388W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YMR243C_YOR316C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YPL134C_YOR222W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YLR333C_YGR027C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YMR142C_YDL082W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YIL053W_YER062C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YAL056W_YOR371C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YNL121C_YHR117W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YML118W_YMR285C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YCL040W_YDR516C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YBR191W_YPL079W_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YDR438W_YML018C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YER102W_YBL072C_gBGC.sh
sbatch -o gBGC-%j.out --mail-type=FAIL --mail-user=xji3@ncsu.edu ./NewRun/YHR139C_YNL160W_gBGC.sh
